### ISSUE TITLE
missing heading errors when running with non-Siemems DICOMS

### ISSUE THREAD

**Issue by switt4** [khanlab/dicom2tar#9]
Hi,

I am running into an error with dicom2tar with trying to run it on non-Siemens DICOM files.  The error has to do with a missing attribute and shows up both on Philips and GE DICOM data.  

The error I get with Philips data is: 
```
AttributeError: 'FileDataset' object has no attribute 'StudyDescription'
2019-11-20 17:56:58,876 - INFO -dicom files no found!
2019-11-20 17:56:58,904 - ERROR -'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dicom2tar/main.py", line 61, in main
    for item in tar_full_filenames:
TypeError: 'NoneType' object is not iterable 
```

Happy to supply the DICOM files in question.

cheers.

suzanne

**Comment by akhanf** [comment]
Looks like the StudyDescription tag is not there -- @yinglilu are you able to look into this? Maybe have a command-line option that sets sensible defaults for the missing required tags?

**Comment by mugxiao** [comment]
Hi Ali,

Just back from group meeting, will look into it.

**Comment by yinglilu** [comment]
Hi Ali,

Just back from group meeting ,will look into it.

**Comment by yinglilu** [comment]
fixed

pip install dicomtar==0.2.0
